/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controller.DrawMaze1;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.event.KeyEvent;
import javax.swing.JFrame;
import model.*;

/**

 @author Omar's PC
 */
public class GameWindow extends javax.swing.JFrame {

    /**
     Creates new form gui
     */
    public static int Height;
    public static int Width;
    private Graphics g;
    public GameWindow() {
        initComponents();
      //  this.setSize(1440, 960);
        this.setResizable(false);
        gameplayPnl.setSize(this.getWidth(), this.getHeight());
        gameplayPnl.setBackground(Color.LIGHT_GRAY);
        DrawMaze1.drawImages(gameplayPnl);
        g = gameplayPnl.getGraphics();
        TreeWall8 test = new TreeWall8();
        test.setI(0);
        test.setJ(0);
        test.draw(gameplayPnl,g);
    }

    /**
     This method is called from within the constructor to initialize the form.
     WARNING: Do NOT modify this code. The content of this method is always
     regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        gameplayPnl = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        xCoord = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        yCoord = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                formKeyPressed(evt);
            }
        });

        gameplayPnl.setForeground(new java.awt.Color(255, 255, 255));
        gameplayPnl.setPreferredSize(new java.awt.Dimension(1400, 950));
        gameplayPnl.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                gameplayPnlMouseMoved(evt);
            }
        });
        gameplayPnl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                gameplayPnlMouseEntered(evt);
            }
        });

        jLabel1.setText("Y");

        jLabel3.setText("X");

        javax.swing.GroupLayout gameplayPnlLayout = new javax.swing.GroupLayout(gameplayPnl);
        gameplayPnl.setLayout(gameplayPnlLayout);
        gameplayPnlLayout.setHorizontalGroup(
            gameplayPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(gameplayPnlLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(gameplayPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(gameplayPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(xCoord, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(yCoord, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(1266, Short.MAX_VALUE))
        );
        gameplayPnlLayout.setVerticalGroup(
            gameplayPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(gameplayPnlLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(gameplayPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(xCoord, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(gameplayPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(yCoord, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(862, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(gameplayPnl, javax.swing.GroupLayout.DEFAULT_SIZE, 1394, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(gameplayPnl, javax.swing.GroupLayout.DEFAULT_SIZE, 944, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_formKeyPressed
        // TODO add your handling code here:
         if (evt.getKeyCode()== KeyEvent.VK_LEFT) {
           System.out.println("LEFT");
    }
    if (evt.getKeyCode()== KeyEvent.VK_DOWN) {
        System.out.println("down");
    }
    if (evt.getKeyCode()== KeyEvent.VK_RIGHT) {
        System.out.println("right");
    }
    if (evt.getKeyCode()== KeyEvent.VK_UP) {
       System.out.println("up");
    }
    }//GEN-LAST:event_formKeyPressed

    private void gameplayPnlMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_gameplayPnlMouseEntered
        // TODO add your handling code here:
       
    }//GEN-LAST:event_gameplayPnlMouseEntered

    private void gameplayPnlMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_gameplayPnlMouseMoved
        // TODO add your handling code here:
         xCoord.setText(String.valueOf(evt.getX()));
         yCoord.setText(String.valueOf(evt.getY()));
    }//GEN-LAST:event_gameplayPnlMouseMoved

    /**
     @param args the command line arguments
     */
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel gameplayPnl;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel xCoord;
    private javax.swing.JLabel yCoord;
    // End of variables declaration//GEN-END:variables
}
